// Code generated by "codegen -type=int /mnt/c/goprogram/src/github.com/wangweihong/eazycloud/internal/pkg/code"; DO NOT EDIT.

package code

// init register error codes defines in this source code to errors package
func init() {
	register(ErrSuccess, 200, map[string]string{"CN": "请求成功", "EN": "Success."})
	register(ErrUnknown, 500, map[string]string{"CN": "服务器出错", "EN": "Internal server error."})
	register(ErrBind, 400, map[string]string{"CN": "解析结构体出错", "EN": "Error occurred while binding the request body to the struct."})
	register(ErrValidation, 400, map[string]string{"CN": "参数校验失败", "EN": "Validation failed."})
	register(ErrTokenInvalid, 401, map[string]string{"CN": "令牌无效", "EN": "Token invalid."})
	register(ErrPageNotFound, 404, map[string]string{"CN": "请求路由不存在", "EN": "Page not found."})
	register(ErrOperationBatchExecute, 200, map[string]string{"CN": "批量执行操作", "EN": "Operation batch execute."})
	register(ErrDatabase, 500, map[string]string{"CN": "数据库出错", "EN": "Database error."})
	register(ErrEncrypt, 401, map[string]string{"CN": "用户密码加密失败", "EN": "Error occurred while encrypting the user password."})
	register(ErrSignatureInvalid, 401, map[string]string{"CN": "签名无效", "EN": "Signature is invalid."})
	register(ErrExpired, 401, map[string]string{"CN": "令牌", "EN": "Token expired."})
	register(ErrInvalidAuthHeader, 401, map[string]string{"CN": "无效的请求授权头部", "EN": "Invalid authorization header."})
	register(ErrMissingHeader, 401, map[string]string{"CN": "请求授权头部为空", "EN": "The `Authorization` header was empty."})
	register(ErrPasswordIncorrect, 401, map[string]string{"CN": "密码验证失败", "EN": "Password was incorrect."})
	register(ErrPermissionDenied, 403, map[string]string{"CN": "请求无权限执行", "EN": "Permission denied."})
	register(ErrEncodingFailed, 500, map[string]string{"CN": "数据编码出错", "EN": "Encoding failed due to an error with the data."})
	register(ErrDecodingFailed, 500, map[string]string{"CN": "数据解码出错", "EN": "Decoding failed due to an error with the data."})
	register(ErrInvalidJSON, 500, map[string]string{"CN": "数据非有效JSON结构", "EN": "Data is not valid JSON."})
	register(ErrEncodingJSON, 500, map[string]string{"CN": "JSON数据编码失败", "EN": "JSON data could not be encoded."})
	register(ErrDecodingJSON, 500, map[string]string{"CN": "JSON数据解码失败", "EN": "JSON data could not be decoded."})
	register(ErrInvalidYaml, 500, map[string]string{"CN": "数据非有效YAML结构", "EN": "Data is not valid Yaml."})
	register(ErrEncodingYaml, 500, map[string]string{"CN": "YAML数据编码失败", "EN": "Yaml data could not be encoded."})
	register(ErrDecodingYaml, 500, map[string]string{"CN": "YAML数据编码失败", "EN": "Yaml data could not be decoded."})
	register(ErrHTTPError, 500, map[string]string{"CN": "HTTP请求失败", "EN": "HTTP request error."})
	register(ErrHTTPResponseDataParseError, 500, map[string]string{"CN": "解析HTTP服务返回数据失败", "EN": "Decode data from http response error."})
	register(ErrHTTPClientGenerateError, 500, map[string]string{"CN": "生成HTTP客户端失败", "EN": "Generate HTTP client error."})
	register(ErrGRPCClientGenerateError, 500, map[string]string{"CN": "生成gRPC客户端失败", "EN": "Generate gRPC client error."})
	register(ErrGRPCClientCertificateError, 500, map[string]string{"CN": "gRPC客户端证书错误", "EN": "Validate gRPC client certificate error."})
	register(ErrGRPCClientDialError, 500, map[string]string{"CN": "gRPC客户端连接失败", "EN": "Dial to gRPC server error."})
	register(ErrGRPCClientInvokeServiceError, 500, map[string]string{"CN": "gRPC客户端访问服务接口失败", "EN": "Invoke gRPC server service function error."})
	register(ErrGRPCResponseDataParseError, 500, map[string]string{"CN": "解析gRPC服务返回数据失败", "EN": "Decode data from gRPC service error."})
	register(ErrUserNotFound, 500, map[string]string{"CN": "错误信息未设置", "EN": "Unset error message"})
}
